### ISSUE TITLE
Extend CommonMark.Net with custom rules

### ISSUE THREAD

**Issue by mdmoura** [Knagis/CommonMark.NET#102]
Hello,

Is it possible to extend commonmark.net with custom parsing rules like adding YouTube videos and  so on?

Thank you

**Comment by Knagis** [comment]
Sorry I missed this issue before. The current implementation does not provide any extensibility mechanism. However for individual features there could be different approaches how to solve them. For example, youtube videos could be parsed by using the image url syntax and walking the AST to see if an image URL matches youtube url.
