### ISSUE TITLE
- [ ] Doesn't render a checkbox

### ISSUE THREAD

**Issue by alandball** [Knagis/CommonMark.NET#103]
Pulling and showing GitHub issues and comments on our support page. Updated the package. Version we were using was from March 2015, 0.9.1.

It now renders it as 
![render](https://cloud.githubusercontent.com/assets/519145/20827642/f945be18-b87b-11e6-90f9-a3ddb0ea2bbf.PNG)

Edit: Reverted to 0.9.1 and same behaviour. Sorry to have bothered. I will give this proper attention and figure out what I'm doing wrong.

**Comment by Knagis** [comment]
CommonMark.NET has never supported checkbox syntax. 

It is not part of the [CommonMark specification](http://spec.commonmark.org/).
