### ISSUE TITLE
CommonMark.CommonMarkConvert.Convert() adds two trailing CR/LFs

### ISSUE THREAD

**Issue by Cornan** [Knagis/CommonMark.NET#107]
.Convert() is currently adding two CR/LF pairs at the end of every string.

Is this intentional?  Part of CommonMark? 

For now, I'll strip them off with a Regex, but would be nice to not have to do so.

Thanks!

**Comment by Knagis** [comment]
Duplicate with #105 , already fixed, will be included in the next release.

In short - the two newlines were an error, however one newline will remain.

If you need to remove them, use `TrimEnd()`, not an regexp - it should be much faster.
