### ISSUE TITLE
How is syntax highlighting expected to work?

### ISSUE THREAD

**Issue by jskeet** [Knagis/CommonMark.NET#109]
I'm using Markdown like this:

    ```csharp
    // Some C# code
    ```

And it generates HTML like this:

```html
<pre>
  <code class="language-csharp">
  // Some C# code
  </code>
</pre>
```

That's great in terms of CommonMark.NET parsing - it definitely understands my Markdown properly. But the output isn't syntax-highlighted as I'd like it to be. Is there a known syntax-highlighting library/stylesheet which works well with this? It doesn't seem to be what [Prettify](https://github.com/google/code-prettify) expects, for example.

Apologies if this has already been covered somewhere - I haven't found it in the issues.

**Comment by Knagis** [comment]
[highlight.js](https://highlightjs.org/) supports this syntax for code blocks out of the box.

http://codepen.io/anon/pen/VPdOVo

**Comment by jskeet** [comment]
Great, thanks. I now need to sort out some other aspects of my CSS, but this is great :)

**Comment by tiesont** [comment]
Prism.js will also work: http://prismjs.com/
