### ISSUE TITLE
Image source containing spaces are not supported

### ISSUE THREAD

**Issue by sandrock** [Knagis/CommonMark.NET#113]
The following MD syntax does nothing:

    ![my picture](my picture.png)

The following works:

    ![my picture](my%20picture.png)

It looks like something prevents spaces in the picture path. It is not OK to ask users to escape spaces. 

Here is a temporary workaround I'm using...

``` c#
var imgRegex = new Regex(@"!\[([^]]+)\]\(([^\)]+)\)");
content = imgRegex.Replace(content, match =>
{
    var alt = match.Groups[1].Value;
    var href = match.Groups[2].Value.Replace(" ", "%20"); // fix for CommonMark
    var final = "![" + alt + "](" + href + ")";
    return final;
});
var html = CommonMark.CommonMarkConverter.Convert(content, md);
```

I tried try make a fix by myself but did not have time to understand the source codes.

**Comment by Knagis** [comment]
This is correct according to the spec: http://spec.commonmark.org/dingus/?text=!%5Bmy%20picture%5D(my%20picture.png)

As such this issue should be raised against the spec, not this implementation. See also this discussion: https://talk.commonmark.org/t/allowing-whitespaces-in-link-urls/2386/2
