### ISSUE TITLE
Some KUDOS to you :) - && a feature request

### ISSUE THREAD

**Issue by polterguy** [Knagis/CommonMark.NET#114]
You can find it at the bottom of my blog attached further down. Basically, I have wrapped your library, into an Active Event called **[markdown2html]**, which internally consumes your library.

[KUDOS](https://gaiasoul.com/2017/06/24/increase-your-software-development-productivity-100x/)

PS! (feature request)
I'd love to be able to have optionally different two URL resolvers, one for images, and another one for hyperlinks. Would that be a drag ...?

Pliiis ...? :)

**Comment by Knagis** [comment]
That could be achieved right now with the use of `Block.AsEnumerable()`, see the example in wiki: https://github.com/Knagis/CommonMark.NET/wiki#blockasenumerable

**Comment by polterguy** [comment]
Thx :)
