### ISSUE TITLE
Razor-style templating

### ISSUE THREAD

**Issue by firelizzard18** [Knagis/CommonMark.NET#14]
I am looking to create a view controller that uses markdown files with Razor-style embedded C# to create templates. I want to translate the markdown parts of the view into html using CommonMark.NET, with the C# sections embedded as string literals. I plan to Emit classes that contain the rendered markdown as static strings that are written to the output stream, interspersed with C#. E.G. this:

```
@{
	CommonMarkSettings.UrlResolver = VirtualPathUtility.ToAbsolute;
	var count = Model.Messages.Count();
}

Home
----

You have [@count unread messages](~/Messages).
```

Would result in an emitted class equivalent to this:

```
class Home_CSMD__DB7A756A_1901_4800_9C36_F8037D40697B
{
	public static readonly DateTime DateCreated;

	public void Write(TextWriter writer)
	{
		CommonMarkSettings.UrlResolver = VirtualPathUtility.ToAbsolute;
		var count = Model.Messages.Count();

		writer.Write("<h1>Home</h1>");
		writer.Write("<p>You have <a href='{0}'>{1} unread messages</a>.</p>", CommonMarkSettings.UrlResolver("~/Messages"), count);
	}
}
```

I want to parse and render the markdown once per file version, so using T4 to generate an intermediate step that is then parsed by CommonMark.NET is not an option. Since Issue #4 and #5 make it clear that you have no plans to support extensibility, I assume my best option is to fork CommonMark.NET? Can you tell me where the best place to add such extensions in your code would be?

Full disclosure: I would be doing this as part of a project for my employer and might not be able to release the source of my modifications.

**Comment by Knagis** [comment]
If you need any more information, feel free to reopen the issue.

**Comment by firelizzard18** [comment]
Thanks. I'll be working on this again in the future, but it's low priority ATM.
