### ISSUE TITLE
Can I use this parser to create my own output format?

### ISSUE THREAD

**Issue by dirkrombauts** [Knagis/CommonMark.NET#15]
If I want to use my own output format, like for instance formatted text in a WPF textblock - can I use this parser to parse/tokenize markdown files?

**Comment by Knagis** [comment]
Yes, you would use `CommonMarkConverter.ProcessStage1()` and `ProcessStage2()` to create the document element tree (AST) and then pass that to your own writer/renderer implementation.

See [`Printer.PrintBlocks`](https://github.com/Knagis/CommonMark.NET/blob/master/CommonMark/Formatter/Printer.cs#L47) on how the writer can be implemented without recursion.

**Comment by dirkrombauts** [comment]
Cool, thanks!
