### ISSUE TITLE
Provide "Parse" method to return a syntax tree

### ISSUE THREAD

**Issue by sharwell** [Knagis/CommonMark.NET#19]
It would be nice if a `Parse` method was provided in addition to the current `Convert` method, which converts input to a syntax tree instead of rendering it to text.

Of course the current code can produce this result, but it requires the user knowing to call `ProcessStage1` and `ProcessStage2`, but not `ProcessStage3`.

**Comment by Knagis** [comment]
Yes, this would be reasonable.

Also `ProcessStage1/2` could be marked as advanced for the intellisense while `Parse` would be not. Though this only impacts VB intellisense, for some reason, C# developers are all considered to be experts that have to see every member...
