### ISSUE TITLE
Consider updating license to 2-clause BSD

### ISSUE THREAD

**Issue by sharwell** [Knagis/CommonMark.NET#20]
The reference code for the C version of the parser was recently relaxed slightly to use the 2-clause BSD license (see https://github.com/jgm/cmark/commit/58ce8ce3600a125aee8579a37b92474ebb4e8308). Would you consider updating the license for this parser to match?

If not please include a note in this issue, which would serve as a reference for future readers. :+1:

**Comment by Knagis** [comment]
I am not really sure what benefit (or drawback) would that give anyone... Could you give an example case where you need this change?

I am not against it, it is just easier not to change :smile:

**Comment by sharwell** [comment]
The wording of the 2-clause license more closely resembles the X11 license (aka the MIT license), which allows it to be more easily integrated with certain other code, including but not limited to code using the MIT license. :+1:

**Comment by Knagis** [comment]
The current license does not prohibit such use. How exactly would the use of MIT wording make it easier? The notice would still have to be included in derived works...

**Comment by sharwell** [comment]
I deleted my post above. At the moment, I do not see the current license causing any problems.
