### ISSUE TITLE
When Block.Tag == BlockTag.AtxHeader, Block.SourceLength = 0

### ISSUE THREAD

**Issue by mike-ward** [Knagis/CommonMark.NET#22]
I'm using the very cool source position tracking. Is it expected that `Block.SourceLength` is zero for `BlockTag.AtxHeader`?

**Comment by Knagis** [comment]
No, that is a bug. I think it is the same reason why `<hr/>` elements had zero length - they start and end on the same line. I will make a generic fix for this, probably today.

**Comment by mike-ward** [comment]
I'm still getting `SourceLength = 0` in AtxHeaders in version 0.8.1. Regards...

**Comment by Knagis** [comment]
Hmm... Could it be that I didn't rebuild the proper configurations before packaging? :fearful:

**Comment by Knagis** [comment]
0.8.2 uploaded. I did indeed incorrectly publish an older version. Thanks for the heads up!

**Comment by mike-ward** [comment]
That fixes it. Thanks!
