### ISSUE TITLE
tag length limit 10???

### ISSUE THREAD

**Issue by dornstein** [Knagis/CommonMark.NET#28]
My markdown sometimes includes tags that I want passed through but they are longer than 10 characters.  The hard coded limit of 10 characters is a problem and the parser just ungracefully crashes.  I can deal with catching the parser failure, but is there some reason the tag name length is fixed here?  Couldn't this just build a string of effectively unlimited length?

The problem appears to be line 153 in the scanner:

    var tagname = new char[10];

**Comment by Knagis** [comment]
Which version of the library are you using? This was fixed in #16 (v0.6.1). 

The char[10] is there because the longest block tag name is 10 char long (`blockquote`) and the scanner stops after 10 chars (anything longer does not start a html block).
