### ISSUE TITLE
CommonMarkConverter Exception in ProcessingStage1

### ISSUE THREAD

**Issue by mike-ward** [Knagis/CommonMark.NET#30]
The text

    * *

(two astericks separated by a space)

causes the following exception:

CommonMark.CommonMarkException was unhandled
Message: An unhandled exception of type 'CommonMark.CommonMarkException' occurred in CommonMark.dll
Additional information: An error occurred while finalizing open containers.

Steps to reproduce:

- Install Markdown Edit 1.3.3 (https://github.com/mike-ward/Markdown-Edit/releases/download/v1.3.3/MarkdownEditSetup.msi)
- Run
- Press Ctrl+N to create a new document
- Type `* *` in the editor window

The program faults in  CommoinMarkConverter.ProcessingStage1.

**Comment by Knagis** [comment]
Version 0.8.4 with the fix has been released.

**Comment by mike-ward** [comment]
Cool beans! Thanks...
