### ISSUE TITLE
Target Frame for InlineContentLinkable

### ISSUE THREAD

**Issue by UweKeim** [Knagis/CommonMark.NET#33]
What I want to do is to be able to make _all_ URLs open in a new tab/window.

So I tried your #4 and found that `InlineContentLinkable` only supports the URL and the title.

**My question:**

Any chance to have a future version support passing targets during rendering stage?

**Comment by Knagis** [comment]
I think that #31 would solve this particular issue for you once it is finished.

**Comment by UweKeim** [comment]
Thanks!

**Comment by Knagis** [comment]
0.9.0 has been relased with the HtmlFormatter class that enables this functionality.

**Comment by Knagis** [comment]
Exmaple how to achieve this: <https://github.com/Knagis/CommonMark.NET/wiki>

**Comment by UweKeim** [comment]
That's awesome. Thanks a lot for making this possible.
