### ISSUE TITLE
Change from MSUnit to NUnit/XUnit?

### ISSUE THREAD

**Issue by yetanotherchris** [Knagis/CommonMark.NET#36]
Are there any plans to switching the unit testing framework from MSTest to NUnit or XUnit? The latter work a bit better with CI servers (I'm thinking of Travis), for example I managed to get a build passing on Travis with a few bits of search and replace:

- https://travis-ci.org/yetanotherchris/CommonMark.NET/builds/56018212
- https://github.com/yetanotherchris/CommonMark.NET/commits/master

You can get a free copy of Resharper if you have an OS project, if running the tests on your own machine inside Visual Studio is the issue.

**Comment by Knagis** [comment]
I think that the ability of running the tests in Visual Studio out of the box without any plugins is a must-have. Resharper gives licenses only to core developers of the project, not everyone who would like to fork the project.

But I am open to a solution that would enable the tests to be run from both frameworks. Using type forwards or custom attributes and separate test class for each framework or another solution. The goal would be to have that portability code in one place, not in each file.

**Comment by 304NotModified** [comment]
Running the unit tests on a build Server (e.g. Travis) is more important than running them local IMO.

**Comment by yetanotherchris** [comment]
I had a try at toggling between the two via reference conditionals in the project file,  and compilation symbols, but it's way too dirty and annoyingly `Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute` etc. are sealed classes:

	#if NUnit
	using NUnit.Framework;
	#else
	using Microsoft.VisualStudio.TestTools.UnitTesting;
	#endif

	namespace CommonMark.Tests
	{
	#if NUnit
		public class TestClassAttribute : TestFixtureAttribute
		{	
		}

		public class TestMethodAttribute : TestAttribute
		{
		}

		public class TestCategoryAttribute : CategoryAttribute
		{
			public TestCategoryAttribute(string name) : base(name.Replace("-", ":"))
			{
			}
		}

		public class Assert : NUnit.Framework.Assert
		{
		}
	#else
		using TestClassAttribute : Microsoft.VisualStudio.TestTools.UnitTestingTestClassAttribute
		{
		}

		public class TestMethodAttribute : Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute
		{
		}

		public class TestCategoryAttribute : Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute
		{
		}

		public class Assert : Microsoft.VisualStudio.TestTools.UnitTesting.Assert
		{
		}
	#endif
	}

Both XUnit and NUnit have runners that integrate into Visual Studio, they're just not as good as the Microsoft.TestTools or Resharper one. But as you've got a .KProject already, I think it's a bit weird to use MS Test as the project will never build outside of Windows like this, and XUnit is built into Visual Studio 2015.

It's not a big issue though, a "nice to have" :)

**Comment by Knagis** [comment]
What problems did you have with the MSTest in the CI environment? Some time ago I did try to compile the project on Mono and it worked well including the tests that I was able to execute simply on command line (if I remember correctly).

**Comment by sharwell** [comment]
@Knagis I've had great success with xunit and would recommend it from the alternatives discussed here. I don't use ReSharper; the xunit integration with Visual Studio 2012+ has been great right out-of-the-box. In fact, for at least Visual Studio 2013 and Visual Studio 2015, the xunit test runner for Visual Studio doesn't even need to be installed by the user because you can just add it as a NuGet dependency.

**Comment by radenkozec** [comment]
@yetanotherchris @Knagis I don't see the point changing Tests from MSTest to XUnit just for fun.
I used both and MSTest is perfectly fine and can be configured to run on any CI easily.
Better to focus on more important things.

**Comment by 304NotModified** [comment]
FYI: Microsoft is also moving from mstest to xUnit. 

>Mstest ([TestClass], [TestMethod]) was the default testing framework for Visual Studio so far.

>ASP.NET 5 and VS 2015 uses xUnit.net as a unit test framework. This framework uses the [Fact] attribute. Support for Mstest still exists.

http://weblogs.asp.net/dotnetstories/what-is-new-in-asp-net-5-and-mvc-6

**Comment by 304NotModified** [comment]
Of course there should be a great benefit to move to xUnit.  If this unit tests are now running correctly on the CI server,  then I don't think moving is needed for now.

**Comment by Knagis** [comment]
I configured CI with the current tests on AppVeyor so the CI argument seems redundant.

Unless someone comes up with a good argument for the migration, I think the tests should be left as is.

**Comment by 304NotModified** [comment]
Agree with that

**Comment by yetanotherchris** [comment]
If you've got AppVeyor setup then it's not an issue anymore
