### ISSUE TITLE
Advice please - offset heading levels

### ISSUE THREAD

**Issue by dornstein** [Knagis/CommonMark.NET#38]
I'm currently using CommonMark.NET and I have a scenario I'm trying to enable, but I'm not sure how to approach.  In short, I need to be able to offset the levels of the generated heading levels.  Normally when I run a string through I expect a '#' to generate an H1 and '##' to generate H2, etc.  But sometimes I'm going to be embedding the generated HTML into a context in which there is already an H1 (or an H2, etc.).  So what I'd ideally like is some way to pass in a headingOffsetLevel that would by default be 0 but I could pass in a 1 to make '#' generate H2s, a 2 to make '#' generate H3s, etc.

I haven't gone into the CommonMark code yet to try to understand how to approach this.  I'd appreciate any input about the best way to approach this.  Assuming such a magic parameter isn't already built in, would there be a best way to leverage one of the extensibility mechanisms for this?

**Comment by Knagis** [comment]
You can use the `AsEnumerable` to modify the parsed document:

```c#
// parse markdown into document structure
var document = CommonMarkConverter.Parse("[click this link](~/hello)");

// walk the document node tree
foreach (var node in document.AsEnumerable())
{
    if (
        // start and end of each node may be visited separately
        node.IsOpening
        // blocks are elemets like paragraphs and lists, inlines are elements like emphasis, links, images.
        && node.Block != null 
        && (node.Block.Tag == BlockTag.AtxHeader || node.Block.Tag == BlockTag.SETextHeader))
    {
        node.Block.HeaderLevel += 2;
    }
}

using (var writer = new System.IO.StringWriter())
{
    // write the HTML output
    CommonMarkConverter.ProcessStage3(document, writer);
    Console.WriteLine(writer.ToString());
}
```
