### ISSUE TITLE
Project no longer builds in VS2013

### ISSUE THREAD

**Issue by lostfictions** [Knagis/CommonMark.NET#40]
Looks like abf31ed9776ec9115c5a4b6e97a0254ea9cf217e introduced a bunch of uses of `nameof`, which is a C# 6 feature not available in Visual Studio 2013. (According to [this](https://stackoverflow.com/questions/27093908/how-to-enable-c-sharp-6-0-feature-in-visual-studio-2013) there was an end user preview that enabled its use in VS2013, but it's long been out-of-date and has since been closed entirely.)

Unfortunately, that means the project simply won't build in anything other than VS2015, despite what the readme suggests.

**Comment by Knagis** [comment]
Is there a reason why you wouldn't be able to use VS2015 community to work with this project?
