### ISSUE TITLE
Add option to include ID in headers

### ISSUE THREAD

**Issue by dscoduc** [Knagis/CommonMark.NET#44]
Markdown pages that contains links which point to headers don't convert correctly.  The links are 
translated correctly but the headers don't get the ID value in order for the links to hook up correctly.

Example of source:
```
## Table of Contents
* **[Solution Overview](#solution-overview)**

## Solution Overview
```
Example of desired results:
```
<h2>Table of Contents</h2>
<ul>
    <li><a ref="#solution-overview">Solution Overview</a></li>
</ul>

<h2 id="soluton-overview>Solution Overview</h2>
```

**Comment by Knagis** [comment]
This behavior is according to the specification:
<http://spec.commonmark.org/dingus/?text=%23%23%20Table%20of%20Contents%0A*%20**%5BSolution%20Overview%5D(%23solution-overview)**%0A%0A%23%23%20Solution%20Overview> 

See also the discussion on [talk.commonmark.org](http://talk.commonmark.org/t/feature-request-automatically-generated-ids-for-headers/115).

What you can do is provide a custom [HtmlFormatter](https://github.com/Knagis/CommonMark.NET/wiki#htmlformatter) implementation that would add the `id` attributes to header elements.

**Comment by dscoduc** [comment]
Thank you for the response.  I looked at the HtmlFormatter and was unable to decipher how to use that for making the change I needed.  Would you have any example code that might shed more light on doing my task?


 ___  _          _
/ __|| |_   _ _ (_) ___
| (__ | ' \ | '_|| |(_-<
\___||_||_||_|  |_|/__/
__________________________
< Tm8gbW9yZSBzZWNyZXRzCg== >
--------------------------
       \   ^__^
        \  (@@)\_______
           (__)\       )\/\
               ||----w |
               ||     ||

**Comment by Knagis** [comment]
```c#
protected virtual void WriteBlock(Block block, bool isOpening, bool isClosing, out bool ignoreChildNodes) 
{ 
    if (isOpening && (block.Tag == BlockTag.AtxHeader || block.Tag == BlockTag.SETextHeader)) {
        this.Write("<h" + block.HeaderLevel.ToString() + " id=\"" + generateId(block) + "\">");
        ignoreChildNodes = false;
    }
    else
    {
        base.WriteBlock(block, isOpening, isClosing, out ignoreChildNodes);
    }
}
```

you would have to implement `generateId()` method that creates the ID in format you require by looking at the child elements of the header.
