### ISSUE TITLE
Unable to parse syntax highlighting after html tag

### ISSUE THREAD

**Issue by cnblogs-dudu** [Knagis/CommonMark.NET#45]
The following markdown cannot be parsed. 
<img width="400" alt="screen shot 2015-09-30 at 18 53 12" src="https://cloud.githubusercontent.com/assets/3196961/10191213/8b315e88-67a4-11e5-95ff-3fe8fb25b286.png">

**Comment by Knagis** [comment]
This is due to the fact that CommonMark.NET has not been updated to the new HTML tag parsing rules.

<https://github.com/Knagis/CommonMark.NET/issues/39>

I do hope to find time for this sometime soon.
