### ISSUE TITLE
proper handling of <!-- --> comments

### ISSUE THREAD

**Issue by midiway** [Knagis/CommonMark.NET#47]
C# test code:
```c#
string output = CommonMark.CommonMarkConverter.Convert(@"
<!--
line1

line2
-->
");
```
HTML output is:
```HTML
<!--
line1
<p>line2
--&gt;</p>
```

If you remove that blank line from the input, between line1 and line2, it will work, so the problem is that blank lines are starting a new paragraph, even though you are inside a HTML comment tag

**Comment by Knagis** [comment]
This is another issue that is there because the HTML tag parser has not been updated: #39
