### ISSUE TITLE
Fix appveyor build

### ISSUE THREAD

**Issue by Knagis** [Knagis/CommonMark.NET#49]
The newest nuget no longer plays nice with all the project files being in the same folder - it tries to load project.json for non-DNX projects and fails.

```
C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(89,5): error : Couldn't find the required information in the lock file. Make sure you have .NETPortable,Version=v4.0,Profile=Profile328 mentioned in your targets. [C:\projects\commonmark-net\CommonMark\CommonMark.Base.csproj]
```

Since nuget package restore is not used, the `Microsoft.NuGet.targets` file should not be run at all. It is not included in any project file so it probably gets included through some intermediate `.targets` file.

appVeyor config:
```
version: 1.0.{build}
os: Visual Studio 2015
configuration:
- Release
- Debug
environment:
  DNX_FEED: https://www.nuget.org/api/v2
install:
- cmd: >-
    set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

    dnvm install latest -r coreclr -a x86 -NoNative

    dnvm install latest -r clr -a x86 -NoNative

    dnu restore
build:
  parallel: true
  verbosity: minimal
```

**Comment by dmitry-shechtman** [comment]
Fixed in https://github.com/Knagis/CommonMark.NET/commit/971609ac2e37a79897a9f8a5fa2cb16ae78b35c0

**Comment by Knagis** [comment]
I was hoping that nuget team would have fixed this in VS2015 Update 1 but when I tested they did not. At least the obvious fix works... :)
