### ISSUE TITLE
Html block in code span is interpreted as markup

### ISSUE THREAD

**Issue by mike-ward** [Knagis/CommonMark.NET#50]
Steps to reproduce.

- Install latest Markdown Edit (http://mike-ward.net/downloads)
- Open latest CommonMark spec in Markdown Edit

Result - All paragraphs are red.

Possible cause: There's a  &lt;style&gt; tag at line 2033. It's inside a code span but appears to be interpreted as a style block.

Markdown Edit is using the latest version of CommonMark.NET.

*Note: I tried to repro this with CommonMark.NET console but I couldn't get the current package to build due to issues with DNX core.*

![image](https://cloud.githubusercontent.com/assets/567927/11021089/9192c39c-8604-11e5-873c-48ed9d2b2bbd.png)

**Comment by Knagis** [comment]
Created an issue on the CommonMark repo. The problem is that those are not code blocks in the spec.txt file - basically the specification is not a markdown file - instead those are special directives that their HTML generation process recognizes.

**Comment by mike-ward** [comment]
I thought that code looked a bit odd...

**Comment by Knagis** [comment]
From the linked issue
 > spec.txt  isn't intended to be interpreted as a Markdown file.
 > If you want a Markdown version, do  make spec.md .
