### ISSUE TITLE
Subscript tilde

### ISSUE THREAD

**Issue by dmitry-shechtman** [Knagis/CommonMark.NET#52]
Hi @Knagis,

As mentioned elsewhere, I managed to add ^superscript^ and ~subscript~, and both work well, although they don't yet conform to the Pandoc spec, which permits no unescaped spaces between the delimiters.

The superscript was the easiest part, although the subscript wasn't too hard as well - I basically created a replica of `HandleEmphasis` with only minor changes.

However, there's a problem. Since the tilde is already taken by strikeout, I can't disable strikeout while subscript is enabled. I tried the following:

```C#
    InlineTag? doubleCharTag = InlineTag.Strikethrough;
    if (0 == (settings.AdditionalFeatures & CommonMarkAdditionalFeatures.StrikethroughTilde))
        doubleCharTag = null;
```

but that causes an `InvalidOperationException (Nullable object must have a value)` here:

```C#
    inl.Tag = useDelims == 1 ? singleCharTag.Value : doubleCharTag.Value;
```

Any ideas? Thanks.

**Comment by Knagis** [comment]
I think that you should just add 

```c#
if (useDelims === 2 && doubleCharTag == null)
    useDelims = 1;
```

before line 307: https://github.com/Knagis/CommonMark.NET/blob/master/CommonMark/Parser/InlineMethods.cs#L307

If that does not help, let me know.

**Comment by dmitry-shechtman** [comment]
Thanks! The exception is gone, but now I'm getting `<sub><sub>inline</sub></sub>`...

**Comment by Knagis** [comment]
If `~foo~` is converted to `<sub>foo</sub>` then `~~foo~~` would turn into `<sub><sub>foo</sub></sub>`. You could try specifying `doubleCharTag` as well (if strikethrough is not enabled) but note that `~~~foo~~~` would still be parsed with nested `<sub>` elements.

**Comment by dmitry-shechtman** [comment]
Thank again.
Is that the spec-defined behavior?

**Comment by Knagis** [comment]
That is hard to say since the cases in the spec has both single and double characters for emphasis. But for them this behavior is defined this way - the markers can be nested however deep is required, so `****foo****` is `<strong><strong>foo</strong></strong>` - so the same idea is applied to cases when only the single char marker is defined.

**Comment by dmitry-shechtman** [comment]
Something like this does make sense for subscript:

    E~a~i~~

but I believe

    ~~foo~~

shouldn't be nested.

Maybe I'll just leave it for now.
Thanks, I really appreciate your help.

**Comment by dmitry-shechtman** [comment]
So as you might have seen, I sent you a pull request, which means I consider this issue resolved :+1:
