### ISSUE TITLE
Output different than CommonMark dingus

### ISSUE THREAD

**Issue by mike-ward** [Knagis/CommonMark.NET#60]
The markdown text:

```
##### Relativity
---

##### Quadratic Equation
---

##### Cauchy's Integral Formula
---
```
outputs

```
<h5>Cauchy's Integral Formula</h5>
<hr>
```

This output is missing serveral elements.

The CommonMark.org dingus emits the expected out.

P.S. I couldn't build CommonMark.Net's console program due to packaging  errors (something with DNX Core won't package restore) so I'm using the lastest build of Markdown Edit, which uses the latest build of CommonMark.Net.

**Comment by Knagis** [comment]
I will look into this.

P.S. You can just unload the DNX project and it should build. It took me most of the night to get it working on my machine.

**Comment by mike-ward** [comment]
Ah, that's the secret. I was trying to use the SDK.

**Comment by Knagis** [comment]
I just added the test and it does not fail. Could you double check your code? Also note that the nuget package includes a command line executable that you can use to test the library.

**Comment by mike-ward** [comment]
OK, I'll see if I can repro it in a small sample.

**Comment by mike-ward** [comment]
Yeah, it's my bug. Sorry to bother you about this. Knowing that there's a command line util was helpful.
