### ISSUE TITLE
Custom containers

### ISSUE THREAD

**Issue by dmitry-shechtman** [Knagis/CommonMark.NET#65]
Hey,

I'm trying to add `:::` custom containers (similar to [markdown-it](https://github.com/markdown-it/markdown-it-container)).

[This](https://github.com/AMDL/CommonMark.NET/tree/div) is where I got so far. Child _inlines_ seem to work OK, but child _blocks_ don't (I only need paragraphs as a minimum requirement).

Any help would be greatly appreciated.

**Comment by dmitry-shechtman** [comment]
Never mind. Now that I've done a complete rewrite of IncorporateLine(), I think I've got an idea or two.

**Comment by Knagis** [comment]
Sounds very promising! Hats off to you for doing this! Unfortunately it seems that the CommonMark spec development has stalled so extensions is the only way to move forward.

**Comment by dmitry-shechtman** [comment]
The spec may be stalled, but the implementation doesn't need to be.

How should we proceed? The changes I've made are pretty heavy (and there's
still work to do). Will you consider adding me as co-author or would it be
better for all involved if those were released separately?

**Comment by Knagis** [comment]
I gave you write access to this repository. I think that it would be better for no one if we start creating two different releases.

**Comment by dmitry-shechtman** [comment]
Thanks. I really appreciate your input on my contribution, past and future.

You may see the progress I've made so far in the (inappropriately named)
pipe-tables branch.
