### ISSUE TITLE
DNX Core 5.0 reference not found on solution open

### ISSUE THREAD

**Issue by ruffin--** [Knagis/CommonMark.NET#66]
AIA.

I pulled and opened CommonMark.NET in VS 2015 Community on Windows 8.1, and the CommonMark.NETCore project is missing its references related to DNX Core 5.0, and is therefore unbuildable for me.

![commonmarkissues](https://cloud.githubusercontent.com/assets/5659878/11762764/217eddee-a0c0-11e5-8c82-13b3cea47e5d.png)

A little not-that-helpful googling suggests DNX Core is a platform-neutral-ish subset of the .NET runtime, but [most of the hits for searching it and "install"](https://duckduckgo.com/?q=%22dnx+core+5.0%22+install&t=ffsb) (that I found) seem to suggest its ASP.NET related. ?? The only DNX related open issue in CommonMark now is [this one](https://github.com/Knagis/CommonMark.NET/issues/49), which is unrelated, and [there are no closed that seem related either](https://github.com/Knagis/CommonMark.NET/issues?utf8=%E2%9C%93&q=is%3Aissue+dnx+).

What do I need to do to get this CommonMark prereq configured correctly?

**Comment by Knagis** [comment]
It should be enough to run these commands in the command line:

    dnvm install latest -r coreclr -a x86 -NoNative
    dnvm install latest -r clr -a x86 -NoNative
    dnu restore

The first ones install the DNX runtime (only the coreclr should be needed but who knows with DNX) the last one should restore any dependencies. 

I am open to proposals on how to make it easier to use the coreclr project.
