### ISSUE TITLE
Extra spaces before indented code in a list

### ISSUE THREAD

**Issue by dmitry-shechtman** [Knagis/CommonMark.NET#69]
[The latest addition](https://github.com/jgm/CommonMark/pull/384) to the spec seems to fail.

Expected:
```
<ul>
<li><p>Foo</p>
<pre><code>bar

baz
</code></pre></li>
</ul>
```

Actual:
```
<ul>
<li><p>Foo</p>
<pre><code>  bar

  baz
</code></pre></li>
</ul>
```

P.S. Is there a way to remove the extra `<` and `>` from test output? Those are _really_ annoying.

**Comment by Knagis** [comment]
> P.S. Is there a way to remove the extra < and > from test output? Those are really annoying.

What do you mean by this?

**Comment by dmitry-shechtman** [comment]
The test output looks like this:

    Actual: <<p>foo</p>>

Maybe you could get used to that, but I find it quite annoying (e.g. when pasting a longish output into an issue).

**Comment by Knagis** [comment]
If I understand correctly, those are added by VS in the test explorer. If you click on the `Output` link you will see the log that does not have them (though it replaces tabs and spaces with special chars).

**Comment by dmitry-shechtman** [comment]
`Output` is where I copy the output from. Apparently, those **are** added by VS, but at a somewhat earlier stage.

**Comment by dmitry-shechtman** [comment]
I must apologize thrice for this.

1. I am sorry for not reading [the topic](http://talk.commonmark.org/t/code-block-with-empty-lines-within-a-list-item/1941) all the way through.
2. I am sorry for overlooking `Specs.tt` (pretty neat stuff BTW).
3. I am sorry for not checking the test output in VS 2015 (yes, I finally made the move).

There's no bug (at least according to jgm), and there's no (more) annoyance.
