### ISSUE TITLE
h1 tag problem

### ISSUE THREAD

**Issue by liamwang** [Knagis/CommonMark.NET#74]
When I input this:
```
<span>Normal span<span>
[Link A](http://xx.com)
<h1>Header 1</h1>
[Link B](http://xx.com)
```

The output string is:
```
<p><span>Normal span<span>
<a href="http://xx.com">Link A</a></p>
<h1>Header 1</h1>
[Link B](http://xx.com)
```
And it displayed like this:
![image](https://cloud.githubusercontent.com/assets/5000396/12410832/ccf881a0-beb3-11e5-9351-d1ea1d38c388.png)
 
The Link B wasn't processed. 
It seams like that all markdown syntax text will not be processed if it after 'h1' tag.

**Comment by Knagis** [comment]
See [try.commonmark.org](http://spec.commonmark.org/dingus/?text=%3Cspan%3ENormal%20span%3Cspan%3E%0A%5BLink%20A%5D(http%3A%2F%2Fxxcom)%0A%3Ch1%3EHeader%201%3C%2Fh1%3E%0A%5BLink%20B%5D(http%3A%2F%2Fxxcom)%0A) - this is according to the specification.

See the [HTML block section in the specification](http://spec.commonmark.org/0.24/#html-blocks) for details.
