### ISSUE TITLE
Why does CommonMark use DNX?

### ISSUE THREAD

**Issue by jez9999** [Knagis/CommonMark.NET#75]
I have no idea why you decided to use DNX for the references in CommonMark.NETCore.  I see no real benefit in using it over standard .NET references and it's just giving me a ton of broken references that I'm having a nightmare fixing.

**Comment by Knagis** [comment]
Because it is a version for .NET Core projects. If you need a version for the full framework, you can use any of the other targets that include everything from 2.0 to 4.5. If you want to compile the project on your machine and do not need the Core project, just unload it.
