### ISSUE TITLE
Provide tag helper for aspnet core

### ISSUE THREAD

**Issue by jasonwilliams200OK** [Knagis/CommonMark.NET#82]
From https://github.com/aspnet/Mvc/issues/4473#issuecomment-209892283

> I'm sure at some point in the future someone will create a tag helper for it and put it on NuGet

Would be nice if someone does that once in for example a supplementary `CommonMark.NET.TagHelpers` package (dependency on core CommonMark.NET package) and provide a sample how to configure, reconfigure and use it in a aspnet-core Razor views. :rocket: 

* http://aspnetmvc.readthedocs.org/projects/mvc/en/latest/views/tag-helpers/authoring.html
* https://channel9.msdn.com/Series/aspnetmonsters/Episode-7-Custom-Tag-Helpers

**Comment by Knagis** [comment]
Would this be what you are looking for? 

<https://www.nuget.org/packages/TagHelperSamples.Markdown>

**Comment by Knagis** [comment]
And a blog post that might be useful: http://blog.decayingcode.com/post/creating-a-simple-aspnet-5-markdown-taghelper

**Comment by jasonwilliams200OK** [comment]
Exactly! Sample from https://github.com/dpaquette/TagHelperSamples/blob/master/TagHelperSamples/src/TagHelperSamples.Web/Views/Samples/MarkdownTagHelper.cshtml:

```html
<markdown>
A First Level Header
====================

A Second Level Header
---------------------

Now is the time for all good men to come to
the aid of their country. This is just a
regular paragraph.

The quick brown fox jumped over the lazy
dog's back.
### Header 3
> This is a blockquote.
>
> This is the second paragraph in the blockquote.
>
> ## This is an H2 in a blockquote
</markdown>
```

Thanks @Knagis!
