### ISSUE TITLE
Doesn't recognize italics which end with a single quote

### ISSUE THREAD

**Issue by RareNCool** [Knagis/CommonMark.NET#89]
For example, the string "\*Italic'\*s" will be parsed as:

```
String: *
String: Italic'
String: *
String: s
```

Instead of:
```
Emphasis: Italic'
String: s
```

**Comment by Knagis** [comment]
This is according to the specification. http://spec.commonmark.org/dingus/?text=*Italic%27*s

If you believe that this is not correct, the issue should be raised at the CommonMark repository.
